import type { SelectOption, OnboardingFormData } from "@/app/lib/types/onboarding";

/* ============================================================
   Onboarding — Dropdown Options
   ============================================================ */

export const SKILLS_OPTIONS: SelectOption[] = [
  { value: "web-development", label: "Web Development" },
  { value: "mobile-development", label: "Mobile Development" },
  { value: "data-science", label: "Data Science" },
  { value: "machine-learning", label: "Machine Learning" },
  { value: "ui-ux-design", label: "UI/UX Design" },
  { value: "graphic-design", label: "Graphic Design" },
  { value: "cloud-computing", label: "Cloud Computing" },
  { value: "devops", label: "DevOps" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "project-management", label: "Project Management" },
  { value: "digital-marketing", label: "Digital Marketing" },
  { value: "content-creation", label: "Content Creation" },
  { value: "business-analysis", label: "Business Analysis" },
  { value: "other", label: "Other" },
];

export const EXPERIENCE_OPTIONS: SelectOption[] = [
  { value: "under-graduate", label: "Undergraduate" },
  { value: "recent-graduate", label: "Recent graduate (0–2 years)" },
  { value: "experienced-level", label: "Experienced Level (3–6 years)" },
  { value: "professional", label: "Professional (above 6 years)" },
];

export const GOALS_OPTIONS: SelectOption[] = [
  { value: "new-job", label: "Get a new job", icon: "💼" },
  { value: "new-field", label: "Transition to a new field", icon: "🔄" },
  { value: "school", label: "Go into school", icon: "🎓" },
  { value: "improve-skills", label: "Improve my skills", icon: "⚡" },
];

export const COUNTRIES: SelectOption[] = [
  { value: "worldwide", label: "Worldwide", icon: "🌍" },
  { value: "AF", label: "Afghanistan", icon: "🇦🇫" },
  { value: "AL", label: "Albania", icon: "🇦🇱" },
  { value: "DZ", label: "Algeria", icon: "🇩🇿" },
  { value: "AD", label: "Andorra", icon: "🇦🇩" },
  { value: "AO", label: "Angola", icon: "🇦🇴" },
  { value: "AG", label: "Antigua and Barbuda", icon: "🇦🇬" },
  { value: "AR", label: "Argentina", icon: "🇦🇷" },
  { value: "AM", label: "Armenia", icon: "🇦🇲" },
  { value: "AU", label: "Australia", icon: "🇦🇺" },
  { value: "AT", label: "Austria", icon: "🇦🇹" },
  { value: "AZ", label: "Azerbaijan", icon: "🇦🇿" },
  { value: "BS", label: "Bahamas", icon: "🇧🇸" },
  { value: "BH", label: "Bahrain", icon: "🇧🇭" },
  { value: "BD", label: "Bangladesh", icon: "🇧🇩" },
  { value: "BB", label: "Barbados", icon: "🇧🇧" },
  { value: "BY", label: "Belarus", icon: "🇧🇾" },
  { value: "BE", label: "Belgium", icon: "🇧🇪" },
  { value: "BZ", label: "Belize", icon: "🇧🇿" },
  { value: "BJ", label: "Benin", icon: "🇧🇯" },
  { value: "BT", label: "Bhutan", icon: "🇧🇹" },
  { value: "BO", label: "Bolivia", icon: "🇧🇴" },
  { value: "BA", label: "Bosnia and Herzegovina", icon: "🇧🇦" },
  { value: "BW", label: "Botswana", icon: "🇧🇼" },
  { value: "BR", label: "Brazil", icon: "🇧🇷" },
  { value: "BN", label: "Brunei", icon: "🇧🇳" },
  { value: "BG", label: "Bulgaria", icon: "🇧🇬" },
  { value: "BF", label: "Burkina Faso", icon: "🇧🇫" },
  { value: "BI", label: "Burundi", icon: "🇧🇮" },
  { value: "KH", label: "Cambodia", icon: "🇰🇭" },
  { value: "CM", label: "Cameroon", icon: "🇨🇲" },
  { value: "CA", label: "Canada", icon: "🇨🇦" },
  { value: "CL", label: "Chile", icon: "🇨🇱" },
  { value: "CN", label: "China", icon: "🇨🇳" },
  { value: "CO", label: "Colombia", icon: "🇨🇴" },
  { value: "CD", label: "Congo (DRC)", icon: "🇨🇩" },
  { value: "CR", label: "Costa Rica", icon: "🇨🇷" },
  { value: "HR", label: "Croatia", icon: "🇭🇷" },
  { value: "CU", label: "Cuba", icon: "🇨🇺" },
  { value: "CY", label: "Cyprus", icon: "🇨🇾" },
  { value: "CZ", label: "Czech Republic", icon: "🇨🇿" },
  { value: "DK", label: "Denmark", icon: "🇩🇰" },
  { value: "DO", label: "Dominican Republic", icon: "🇩🇴" },
  { value: "EC", label: "Ecuador", icon: "🇪🇨" },
  { value: "EG", label: "Egypt", icon: "🇪🇬" },
  { value: "SV", label: "El Salvador", icon: "🇸🇻" },
  { value: "EE", label: "Estonia", icon: "🇪🇪" },
  { value: "ET", label: "Ethiopia", icon: "🇪🇹" },
  { value: "FI", label: "Finland", icon: "🇫🇮" },
  { value: "FR", label: "France", icon: "🇫🇷" },
  { value: "GE", label: "Georgia", icon: "🇬🇪" },
  { value: "DE", label: "Germany", icon: "🇩🇪" },
  { value: "GH", label: "Ghana", icon: "🇬🇭" },
  { value: "GR", label: "Greece", icon: "🇬🇷" },
  { value: "GT", label: "Guatemala", icon: "🇬🇹" },
  { value: "HN", label: "Honduras", icon: "🇭🇳" },
  { value: "HU", label: "Hungary", icon: "🇭🇺" },
  { value: "IS", label: "Iceland", icon: "🇮🇸" },
  { value: "IN", label: "India", icon: "🇮🇳" },
  { value: "ID", label: "Indonesia", icon: "🇮🇩" },
  { value: "IR", label: "Iran", icon: "🇮🇷" },
  { value: "IQ", label: "Iraq", icon: "🇮🇶" },
  { value: "IE", label: "Ireland", icon: "🇮🇪" },
  { value: "IL", label: "Israel", icon: "🇮🇱" },
  { value: "IT", label: "Italy", icon: "🇮🇹" },
  { value: "JM", label: "Jamaica", icon: "🇯🇲" },
  { value: "JP", label: "Japan", icon: "🇯🇵" },
  { value: "JO", label: "Jordan", icon: "🇯🇴" },
  { value: "KZ", label: "Kazakhstan", icon: "🇰🇿" },
  { value: "KE", label: "Kenya", icon: "🇰🇪" },
  { value: "KR", label: "South Korea", icon: "🇰🇷" },
  { value: "KW", label: "Kuwait", icon: "🇰🇼" },
  { value: "LV", label: "Latvia", icon: "🇱🇻" },
  { value: "LB", label: "Lebanon", icon: "🇱🇧" },
  { value: "LR", label: "Liberia", icon: "🇱🇷" },
  { value: "LY", label: "Libya", icon: "🇱🇾" },
  { value: "LT", label: "Lithuania", icon: "🇱🇹" },
  { value: "LU", label: "Luxembourg", icon: "🇱🇺" },
  { value: "MG", label: "Madagascar", icon: "🇲🇬" },
  { value: "MY", label: "Malaysia", icon: "🇲🇾" },
  { value: "ML", label: "Mali", icon: "🇲🇱" },
  { value: "MX", label: "Mexico", icon: "🇲🇽" },
  { value: "MA", label: "Morocco", icon: "🇲🇦" },
  { value: "MZ", label: "Mozambique", icon: "🇲🇿" },
  { value: "NP", label: "Nepal", icon: "🇳🇵" },
  { value: "NL", label: "Netherlands", icon: "🇳🇱" },
  { value: "NZ", label: "New Zealand", icon: "🇳🇿" },
  { value: "NG", label: "Nigeria", icon: "🇳🇬" },
  { value: "NO", label: "Norway", icon: "🇳🇴" },
  { value: "PK", label: "Pakistan", icon: "🇵🇰" },
  { value: "PA", label: "Panama", icon: "🇵🇦" },
  { value: "PE", label: "Peru", icon: "🇵🇪" },
  { value: "PH", label: "Philippines", icon: "🇵🇭" },
  { value: "PL", label: "Poland", icon: "🇵🇱" },
  { value: "PT", label: "Portugal", icon: "🇵🇹" },
  { value: "QA", label: "Qatar", icon: "🇶🇦" },
  { value: "RO", label: "Romania", icon: "🇷🇴" },
  { value: "RU", label: "Russia", icon: "🇷🇺" },
  { value: "RW", label: "Rwanda", icon: "🇷🇼" },
  { value: "SA", label: "Saudi Arabia", icon: "🇸🇦" },
  { value: "SN", label: "Senegal", icon: "🇸🇳" },
  { value: "RS", label: "Serbia", icon: "🇷🇸" },
  { value: "SG", label: "Singapore", icon: "🇸🇬" },
  { value: "SK", label: "Slovakia", icon: "🇸🇰" },
  { value: "SI", label: "Slovenia", icon: "🇸🇮" },
  { value: "SO", label: "Somalia", icon: "🇸🇴" },
  { value: "ZA", label: "South Africa", icon: "🇿🇦" },
  { value: "ES", label: "Spain", icon: "🇪🇸" },
  { value: "LK", label: "Sri Lanka", icon: "🇱🇰" },
  { value: "SD", label: "Sudan", icon: "🇸🇩" },
  { value: "SE", label: "Sweden", icon: "🇸🇪" },
  { value: "CH", label: "Switzerland", icon: "🇨🇭" },
  { value: "TW", label: "Taiwan", icon: "🇹🇼" },
  { value: "TZ", label: "Tanzania", icon: "🇹🇿" },
  { value: "TH", label: "Thailand", icon: "🇹🇭" },
  { value: "TT", label: "Trinidad and Tobago", icon: "🇹🇹" },
  { value: "TN", label: "Tunisia", icon: "🇹🇳" },
  { value: "TR", label: "Turkey", icon: "🇹🇷" },
  { value: "UG", label: "Uganda", icon: "🇺🇬" },
  { value: "UA", label: "Ukraine", icon: "🇺🇦" },
  { value: "AE", label: "United Arab Emirates", icon: "🇦🇪" },
  { value: "GB", label: "United Kingdom", icon: "🇬🇧" },
  { value: "US", label: "United States", icon: "🇺🇸" },
  { value: "UY", label: "Uruguay", icon: "🇺🇾" },
  { value: "VE", label: "Venezuela", icon: "🇻🇪" },
  { value: "VN", label: "Vietnam", icon: "🇻🇳" },
  { value: "ZM", label: "Zambia", icon: "🇿🇲" },
  { value: "ZW", label: "Zimbabwe", icon: "🇿🇼" },
];

export const TARGET_ROLES: string[] = [
  "Product Designer",
  "Business Analyst",
  "Marketing Manager",
  "Software Engineer",
  "Data Scientist",
  "Product Manager",
  "UX Researcher",
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer"
];

/** Initial form state with all fields empty. */
export const INITIAL_FORM_DATA: OnboardingFormData = {
  firstName: "",
  lastName: "",
  username: "",
  email: "",
  password: "",
  confirmPassword: "",
  
  location: "",
  experienceLevel: "Student",
  currentRole: "",
  industry: "",
  country: "",
  skills: [],
  
  primaryGoal: "",
  targetRoles: [],
  goalTimeline: "",
} as const;

/** Total number of onboarding steps (Profile, Goals) */
export const TOTAL_STEPS = 2;
